### ISSUE TITLE
update minimum required php version

### ISSUE THREAD

**Issue by henrikbjorn** [silexphp/Silex#1063]
Since Symfony is going in this direction for 3.0 i think we should already consider this for 2.0 and since the development of 2.0 is running long we could also get a cleanup in.

I propose a raise to 5.4 and higher.

what do others think?

**Comment by Atriedes** [comment]
5.5 would be nice

**Comment by fabpot** [comment]
just raised the min version of PHP to 5.5+

**Comment by mediamonks-robert** [comment]
Why set it to 5.5+ while the components relied on (Symfony 2.x) do not require this? Since lots of hosting environments do not support 5.5 yet but do support 5.4 I will have to migrate back from 2.x to 1.x again for upcoming projects. I would have thought that Symfony 3.x would have its own Silex 3.x with matching requirements.

**Comment by henrikbjorn** [comment]
@mediamonks-robert Silex and Symfony does not follow the same versioning.

**Comment by mediamonks-robert** [comment]
It would be nice if it did. Now 1.x is requiring 5.3 and 2.x is directly going for 5.5 while it was 5.4 for as long as it was out there. Because I was assuming it would be 5.4 this will give a lot of issues for our projects which use Silex 2.x for a while now. Now I would need to fall back again to Silex 1.x because of a lack of a clear road map about versions.

**Comment by henrikbjorn** [comment]
@mediamonks-robert the roadmap have been unclear since the start of the 2.0 branch. Im sorry to sound like a douche. But you made a choice to use a development version of a library, and this is some of the things you gotta live with.

**Comment by mediamonks-robert** [comment]
I am aware of that but this makes it very clear that not having a clear roadmap can give issues for end users. 2.x was a good step forward but now it's a step too far for most hosting environments. I am not sure why 5.5 is needed for Silex right now as all components it is relying on are 5.4+ and no 5.5+ features are used. It was 5.4+ for ages and suddenly that changed without any given reason, it just seems like a hasty deciscion without a real reason right now.

**Comment by henrikbjorn** [comment]
@mediamonks-robert 5.6 is the last stable and 7.0 will be out later this year. There is no reason not to use supported and developed versions.

http://php.net/supported-versions.php shows that 5.4 only receives security fixes on a case per case basis.

**Comment by mediamonks-robert** [comment]
I totally agree on the PHP version, it's just that a lot of big corporations won't deliver 5.5 just yet (which is a shame). I guess I'm annoyed by the fact that no roadmap is available, I made some assumptions and suddenly it changes a lot without any reason given :)

**Comment by henrikbjorn** [comment]
@mediamonks-robert which huge corporations? other than maybe shared hosts. 5.5 is even the default you get in the latest ubuntu LTS release (14.04)

**Comment by mediamonks-robert** [comment]
A lot of clients we work for, big brands who handle their own hosting or have it done for them. I am happy they just migrated to 5.4. But nevermind, it's my mistake to make assumption on Silex 2.x progress. I guess I'll have to migrate back to 1.x branch again and rewrite some custom modules. Hopefully next time a roadmap would be really nice to have to prevent such stuff.
