### ISSUE TITLE
What about renaming Api/ to Contract/

### ISSUE THREAD

**Issue by fabpot** [silexphp/Silex#1143]
... like in Laravel?

**Comment by Kilte** [comment]
:+1:

**Comment by Atriedes** [comment]
:+1:

**Comment by GromNaN** [comment]
Or Interface ?

**Comment by davedevelopment** [comment]
Either or for me, I don't mind. Though with the interfaces we actually have, I think API is a better fit, e.g. these are the APIs we provide so that you can create plugins for Silex.

When I think of Contract, I think of it more like the interfaces that Silex is expecting internally etc, e.g. these are Contracts that we will honour, so you can replace or modify components within Silex.
