### ISSUE TITLE
Silex\Application Interface ?

### ISSUE THREAD

**Issue by Atriedes** [silexphp/Silex#1153]
I see there some inconsistency in Silex 2 API

https://github.com/silexphp/Silex/blob/master/src/Silex/Api/EventListenerProviderInterface.php#L24
It require `Pimple\Container` instead `Silex\Application`

But contrary in other two interface
https://github.com/silexphp/Silex/blob/master/src/Silex/Api/BootableProviderInterface.php#L32
https://github.com/silexphp/Silex/blob/master/src/Silex/Api/ControllerProviderInterface.php#L31
It depends on `Silex\Application`.

I think is better to have 1 clean interface for Application for unified those Silex API

**Comment by stof** [comment]
The point is that in implementations of EventListenerProviderInterface, you are not allowed to use the application in other ways than as a pimple container, because it is still called at a time where the container is being built. Depending on the Pimple class here rather than the Silex Application means that providers implementing this interface are more reusable.

On the other hand, BootableProviderInterface and ControllerProviderInterface are specific to Silex, and code implementing these methods is expected to rely on the Silex API (we are not building the container anymore at this time, but other parts of Silex, for instance the router).

Making everything depend on ``Silex\Application`` would mean that all providers are now tied to Silex only again, which is precisely something which has been intentionally changed in Silex 2.

**Comment by stof** [comment]
And adding an interface on ``Silex\Application`` would cause more harm than good IMO: adding new methods in an interface is a BC break because it would break other implementations of the interface. And I don't really see why someone would want to reimplement the Application class in a different way (thus, an interface could not mandate that the implementation extend Pimple, and this is a requirement for Silex anyway)

**Comment by Atriedes** [comment]
I'm currently building apps that extends Silex\Application, and I noticed in PHP they are not able to override interface, thats why this issue was raised. But after reading your comment and make some research there are no benefit to make Interface for Application.

Thanks for your comment by the way
