### ISSUE TITLE
On silex.sensiolabs.org/download the "fat" archive is mostly empty

### ISSUE THREAD

**Issue by Francois6po** [silexphp/Silex#1169]
This seems to be a recurrent problem, but the "fat" silex archive on silex.sensiolabs.org/download is empty (more or less).
I want to try Silex for a new project but I can't use composer on the server.
Any help ?

**Comment by stof** [comment]
The silex archive to start the project is not something you would download on a server anyway, but locally (unless you work on the code directly on the server, but I really hope you don't). 
And the same can be true for Composer. nothing prevents you from uploading your whole local project to the server rather than uploading only your own code and then running composer on the server. This means that the requirement would be to be able to use composer locally, not on the server.

Regarding the download itself, I cannot really help. this must probably be solved by @fabpot who has access to the Silex server.

**Comment by Francois6po** [comment]
I was not speaking of the production server :)
I've just realize that there's a windows installer for composer. I'll try to install it on my desktop.
