### ISSUE TITLE
Recover header of request on error

### ISSUE THREAD

**Issue by silverpark** [silexphp/Silex#1257]
Hi,

When I throw an error why I can't recover the header of request ? ``$oRequest->headers->all()`` equal ``array()``.

```
$oApp->error(function (\Exception $e, $sHttpCode) use ($oApp) {

     $oRequest = Request::createFromGlobals();
     var_dump('error');
     var_dump($oRequest->headers->all());
     die;

});
```

I need that for show a specific error in twig about header content-type (xml, json, html etc...)

How to get ``Symfony\Component\HttpFoundation\Request`` ?

Regards,

Daniel

**Comment by SpacePossum** [comment]
hi,
not sure if it is the best way of doing things in your use case, but you could check if `$oApp['request']` is set.
Btw. you have a better chance of getting a useful answer on a question like this through the mailing list.

**Comment by silverpark** [comment]
Great ! It work !

Thank you.

**Comment by henrikbjorn** [comment]
@silverpark and @SpacePossum `$app['request']` should NEVER be used and is deprecated.

**Comment by silverpark** [comment]
@henrikbjorn, ok but how to get object request on error ? Because only two parameters can be recovered (Exception and codeHttp) ``$oApp->error(function (\Exception $e, $sHttpCode) { ``

**Comment by Kilte** [comment]
@silverpark, you can subscribe to event directly:

```php
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;

$app = new Silex\Application();
$app->on(KernelEvents::Exception, function (GetResponseForExceptionEvent $event) {
    $request = $event->getRequest();
    /* ... */
}, -255);

```

**Comment by SpacePossum** [comment]
I'm puzzled, at http://silex.sensiolabs.org/doc/usage.html there are two samples using this.
At http://silex.sensiolabs.org/doc/services.html
it is listed at `Core services` and lists the error handler as example:

```
request: Contains the current request object, which is an instance of Request. It gives you access to GET, POST parameters and lots more!

Example usage:

$id = $app['request']->get('id');
This is only available when a request is being served; you can only access it from within a controller, an application before/after middlewares, or an error handler.
```

**Comment by henrikbjorn** [comment]
@SpacePossum Using the request from the container leads to synchronization problems if you use subrequests etc.

It exists true, but its a bad practive and should be avoided at any cost.

**Comment by silverpark** [comment]
@Kilte

Yes it's a good idea but ``$event->getResponse()`` equal to ``null``, I need access to ``getStatusCode()``

**Comment by henrikbjorn** [comment]
@silverpark that is because your error handler is called in a subrequest. Therefor Symfony doesnt know about the previous request, and there have been no response yet.

See https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php#L50 for more information.

**Comment by SpacePossum** [comment]
thank you @henrikbjorn for the details!
I think I've some refactoring to do in my error/exception handlers in my projects...   ;)

**Comment by silverpark** [comment]
@henrikbjorn What do you mean about `called in a subrequest` ?

**Comment by henrikbjorn** [comment]
@silverpark In symfony the request flow can happen in two ways. The first is a Master request, which is what you proberly always assume, a request is created from globals and then passed to a controller. However, you can have subrequest. Which is a request created by a controller and is then run isolated from the master request.

Maybe https://knpuniversity.com/screencast/symfony-journey/sub-request-internals will shed some light on it for you. Otherwise there is a chapter in the Silex documentation about making a subrequest. Last, the Symfony documentation also contains some information about this.

**Comment by henrikbjorn** [comment]
@SpacePossum a little advice. Always typehint the Event it self instead of relying on the magic function argument injection. Also it can be easier to create these as "real" EventListeners or Subscribers, that way you have the code isolated and it can also easily be tested without requiring your whole application to be bootstrapped.

**Comment by silverpark** [comment]
@henrikbjorn nice teacher !
