### ISSUE TITLE
how to add more normalizers to 'serializer.normalizers'

### ISSUE THREAD

**Issue by lukaszwit** [silexphp/Silex#1318]
Hi,
symfony serializer component provides a bunch of normalizers but SerializerServiceProvider provides only two of them. I couldn't find a way add more. Is there any way to do this?

**Comment by stof** [comment]
you can do it this way:

```php
$app['serializer.normalizers'] = $app->share($app->extend('serializer.normalizers', function (array $normalizers, $app) {
    $normalizers[] = new CustomNormalizer();

    return $normalizers;
}));
```

On Silex 2, this is even simpler thanks to changes done in Pimple's ``extend`` method (not possible to do them in Pimple 1 due to the internal representation of shared services). You don't need to mark the extended definition as shared again by yourselves as ``extend`` will preserve the shared state:

```php
$app->extend('serializer.normalizers', function (array $normalizers, $app) {
    $normalizers[] = new CustomNormalizer();

    return $normalizers;
});
```

**Comment by ragboyjr** [comment]
@lukaszwit and @stof, can we close this?
