### ISSUE TITLE
Using Swoole with Silex

### ISSUE THREAD

**Issue by casoetan** [silexphp/Silex#1328]
Hi there.

Any ideas on how to use Swoole - http://www.swoole.com - with Silex?

**Comment by GromNaN** [comment]
Swoole is some kind of PHP framework for asynchronous & parallel network communications, written as a C extension for PHP.
The framework contains an **HttpServer** component that is equivalent to the HttpKernel of Symfony. If you can bridge `Request` and `Response` objects between both projects, then they can be used together. Providing a generic Request and Response classes is the purpose of [PSR-7](http://www.php-fig.org/psr/psr-7/) and is implemented in the [Symfony PSR-7 Bridge](http://symfony.com/doc/current/cookbook/psr7.html). An issue has been created on the Swoole repository: https://github.com/swoole/swoole-src/issues/559.

```php
$serv = new swoole_http_server("127.0.0.1", 9502);
$app = new Silex\Application();

$serv->on('Request', function($request, $response) use ($app) {
    $symfonyRequest = convertRequest($request);
    $symfonyResponse = $app->handle($symfonyRequest);
    $response = convertResponse($symfonyResponse);
});
```

Otherwise, you can also use parts of Silex separately with Swoole : 
- Pimple as Service Container
- The Routing component
- The Event Dispatcher component

**Comment by ragboyjr** [comment]
@casoetan, did @GromNaN answer your question sufficiently?

**Comment by casoetan** [comment]
Yes he did.

Thanks

**Comment by kcloze** [comment]
I made a skeleton with swoole as below:
[https://github.com/kcloze/slim-swoole](https://github.com/kcloze/slim-swoole)

**Comment by casoetan** [comment]
nice work @kcloze, but this is for slim not silex. Waiting...
