### ISSUE TITLE
Allow recursive mounting of controller providers

### ISSUE THREAD

**Issue by SpacePossum** [silexphp/Silex#1395]
I try something like this:

```php
$app->mount('/foo/{id}', function ($foo) {
    $foo->mount('/events', new FooEventsProvider());
    $foo->mount('/bars', new FooBarsProvider());
});
```

with both `FooEventsProvider` and `FooBarsProvider` implementing the `ControllerProviderInterface`.
This is not allowed because;
```
The "mount" method takes either a "ControllerCollection" instance or callable.
```

Is it possible to allow `ControllerProviderInterface` as well and call `::connect` on instances of that and mount the return value (`ControllerCollection`) of that?

**Comment by fabpot** [comment]
see #1345

**Comment by 719media** [comment]
I know this issue is closed, but I read over #1345 several times, and have yet to understand what, exactly, the proposed method for handling controllerproviderinterface classes inside of a nested mount is. Borrowing from @SpacePossum comment in that same task:

```
// foo/module/events/test
class FooEventsProvider implements \Silex\Api\ControllerProviderInterface
{
    public function connect(\Silex\Application $app)
    {
        $controllers = $app['controllers_factory'];
        $controllers->get('/test', function($id){ return "events ".$id;});
        return $controllers;
    }
}

//foo/module/bars/test
class FooBarsProvider implements \Silex\Api\ControllerProviderInterface
{
    public function connect(\Silex\Application $app)
    {
        $controllers = $app['controllers_factory'];
        $controllers->get('/test', function($id){ return "bars ".$id;});
        return $controllers;
    }
}

//the below does not work, as FooEventsProvider is not a callable nor a ControllerCollection
$app->mount('/foo/{id}', function ($foo) {
    $foo->mount('/events', new FooEventsProvider());
    $foo->mount('/bars', new FooBarsProvider());
});
```

Soo... was the answer that simply you must define any ControllerProviderInterface classes within $app, and not use nested mounts?

**Comment by mikejw** [comment]
bump.

**Comment by SpacePossum** [comment]
>the proposed method for handling controllerproviderinterface classes inside of a nested mount is

The thing is, there isn't. 
The linked PR shows that the implementation/design choices makes it impossible.
Even if it could work it wouldn't cause the controllers only be created when the route is matched (https://github.com/silexphp/Silex/pull/1345#r70174175) IIRC. This was my first reason to see if this could work, the second that it would be very easy to mount a controller to a different path using a simple lambda.

After given this up I currently use something like;
```php
$app->mount('/foo', new FooController());
$app->mount('/bar', new BarController());
```

Than to safe some overhead on creation of (sub)controllers.
Within `FooController`
```php
    public function connect(Application $app)
    {
        $app['controllers.api'] = $this;
        $app['controllers.api.hardware'] = function () use ($app) {
            return new API\Hardware\HardwareController($app);
        };

        $controllers->get('/hardware', 'controllers.api.hardware:get');
    }
```

This causes `HardwareController` only to be created when GET `/foo/hardware` is hit

**Comment by stof** [comment]
FooController is not a controller in your case. It is a controller provider, which defines some routes. All routes must be defined before starting the matching process, or before starting the URL generation, as they need to know the list of available routes. The definition of routes cannot be done lazily.

**Comment by 719media** [comment]
Ok great, thanks for the feedback all. I have two points from learning about this.

1) For applications with a "lot" of controllers, using the ControllerProviderInterface seems like it could be a bad thing, because if you have a lot of mount points to each individual controller, then you're instantiating a "lot" of controllers on every request to build the routing logic. For this reason, I have not used ControllerProviderInterface classes and instead just stuck with callables.

2) When using named routes, I'm not sure if there is a "best practice" for utilizing the mount point name with the bound name. For example:

```
$app->mount('/green', function ($controllers) use ($app) {
  $app['green.controller'] = function ($app) {
      return new Controllers\IndexController($app);
  };
  $app->get('/view', 'green.controller:viewAction')
      ->bind('green-view');
});
$app->mount('/blue', function ($controllers) use ($app) {
  $app['blue.controller'] = function ($app) {
      return new Controllers\IndexController($app);
  };
  $app->get('/view', 'blue.controller:viewAction')
      ->bind('blue-view');
});
```

In the example above, you can see the same Controller file is used for both mounts. In the scenario where the callable is actually in another file, you can see where having both "green" and "blue" prefixes hardcoded, it makes it hard to re-use. For example:

```
function ($controllers) use ($app) {
  $app['PREFIX.controller'] = function ($app) {
      return new Controllers\IndexController($app);
  };
  $app->get('/view', 'PREFIX.controller:viewAction')
      ->bind('PREFIX-view');
}
```

It would be nice if there was a way to get the prefix for usage in the controller callable (and not just the controllercollection prefix, but the entire prefix from docroot for global namespacing). Is there an established method for this, or is there a different way I should be thinking about this?
