### ISSUE TITLE
Security documentation for password encode process

### ISSUE THREAD

**Issue by Rarst** [silexphp/Silex#1420]
This was my my use case yesterday (first time implementing security stuff in Silex/Symfony–ish way):
1. Implement an optional HTTP authentication in my app
2. Expose a simple configuration to add a single user/password
3. Make it easy for others to setup, document the process

I got to a point of authentication working with provided admin/foo login/hash pair.

Then I looked how can I automate a process of obtaining a password hash.

Then this had me going in circles:

``` php
// find the encoder for a UserInterface instance
$encoder = $app['security.encoder_factory']->getEncoder($user);

// compute the encoded password for foo
$password = $encoder->encodePassword('foo', $user->getSalt());
```

I don't _have_ user. I don't _want_ one. I just want to hash a password. Why do I need salt if salt is not recommended? Why does hash of arbitrary password depends on concrete user instance?

Trait documentation further below failed altogether on unknown `user()` method:

``` php
$user = $app->user();

$encoded = $app->encodePassword($user, 'foo');
```

This is what I ended up with in the end:

``` php
$encoder = $app['security.default_encoder'];
echo  $encoder->encodePassword($password, '');
```

I kinda sorted out (after a while) that user is involved because choice of encoder might be conditional on it, but my impression is that as documented a starter HTTP authentication example is hard to make sense of.

**Comment by cameronjacobson** [comment]
I see that this is an older ticket, so forgive me if you've already worked through this issue.

It's probably going to help if you can explain very explicitly how you're setting this up and what you're trying to do.  I still don't feel like I have a clear idea after reading your ticket.

Perhaps provide a link to your own GitHub repository where your entire project is and point out the specific code that isn't working, and how someone reading this thread could reproduce the problem you're experiencing.

**Comment by Rarst** [comment]
I believe I explained best I could and pointed out specific parts of documentation I had issue with.

If I had to summarize — documentation assumes that you have user(s) set up and code examples are conditional on that, such as `$app->user()` call failing.

For the context I have implemented a very simple case where login/hash pairs are fed in from configuration https://github.com/Rarst/release-belt#authentication

**Comment by cameronjacobson** [comment]
I was unable to find the silex.sensiolabs.org website on github, so I apologize if this response doesn't help.  I wanted to see if current version of the documentation on the silex.sensiolabs.org website is different now than when you first submitted this ticket, so most of the response below is pointing out what the website says assuming it's different now than when you first submitted the ticket.

I would note that the current version of the documentation states:

_The Symfony Security component is powerful. To learn more about it, read the [Symfony Security documentation](http://symfony.com/doc/2.8/book/security.html)._

Part of the confusion might be that you're conflating Silex and the Symfony Security component.  You can "use" the Symfony Security component inside Silex.  It's not mandatory.

Also from the website:

_When a security configuration does not behave as expected, enable logging (with the Monolog extension for instance) as the Security Component logs a lot of interesting information about what it does and why._

If this isn't helpful, the website currently states:

_Need support or have a technical question?
Ask support on Stack Overflow._

I can't speak for SensioLabs of course, but since this ticket hasn't received much attention maybe they interpreted it as a support request.  I certainly read it as such.  If you have specific ideas for how to improve the documentation, once you understand your problem better, maybe this is a good place for something like that?

**Comment by Rarst** [comment]
> I was unable to find the silex.sensiolabs.org website on github

I would guess that would be https://github.com/silexphp/Silex/tree/master/doc

> Part of the confusion might be that you're conflating Silex and the Symfony Security component.

I understand the difference, I am talking about _Silex_ documentation for using Security component in its context.

> I can't speak for SensioLabs of course, but since this ticket hasn't received much attention maybe they interpreted it as a support request. I certainly read it as such.

I had resolved issue I had and explicitly covered how I resolved it in my first message, I require no support on this.

> If you have specific ideas for how to improve the documentation, once you understand your problem better, maybe this is a good place for something like that?

If I was more proficient with Security component I simply would PR possible improvements to documentation. Unfortunately I am not proficient with it to be confident to change docs.

I don't need help or input on this issue. If someone responsible for documentation gets to this they can decide if it's something wort considering for improvement or current state is sufficient and issue can be closed.
