### ISSUE TITLE
Routing does not handle trailing slashes consistently

### ISSUE THREAD

**Issue by AD7six** [silexphp/Silex#149]
This may be merely something to add to the docs.

Using a simple application such as the following:

```
<?php

require_once __DIR__.'/../silex.phar';
use Symfony\Component\HttpFoundation\Response;

$app = new Silex\Application();

$app->get('/', function () use ($app) {
      return new Response('Home root');
});
$app->get('/hello', function () use ($app) {
      return new Response('No trailing slash');
});
$app->get('/hello/', function () use ($app) {
      return new Response('With trailing slash');
});

$app->run();
```

this is the observed behavior:
- http://app/ -> caputured by 'Home' route
- http://app/hello -> caputured by 'No trailing slash' route
- http://app/hello/ -> caputured by 'With trailing slash' route

However expected behaviour would be that the last route is inaccessible:
- http://app/ -> caputured by 'Home' route
- http://app/hello -> caputured by 'No trailing slash' route
- http://app/hello/ -> caputured by 'No trailing slash' route

If the last route is not defined, the result of requesting /hello/ is "Sorry, the page you are looking for could not be found." - but you'd expect it to match the routefor /hello.

This is testing on an arch linux machine running nginx - though that shouldn't really be much of a factor.

**Comment by GDmac** [comment]
Also, parameters are not inserted into the url when the defined bound route has no trailing slash defined
```php
  // Route: $ctl->get('/feed/{duration}', array($this, 'feed'))
  $params = array('duration'=>8);
  $feedlink = $this->app['url_generator']->generate('calendarfeed', $params, true);
  // Gives: http://local.dev/calendar/feed

  // Route: (with trailing slash) $ctl->get('/feed/{duration}/', array($this, 'feed'))
  $params = array('duration'=>8);
  $feedlink = $this->app['url_generator']->generate('calendarfeed', $params, true);
  // Gives: http://local.dev/calendar/feed/8/
```

**Comment by sjparkinson** [comment]
Here's an iteration on @jrschumacher [meta-route above](https://github.com/silexphp/Silex/issues/149#issuecomment-10384486), which doesn't handle GET requests.

```php
// Silex does not handle POST, PUT, and DELETE requests that are missing a trailing
// slash in the url. This meta-route appends the missing slash to such requests.
// See https://github.com/silexphp/Silex/issues/149 for why, tl;dr frameworks are opinionated.
//
// We override the default RedirectableUrlMatcher so that it doesn't respond with 301 to GET requests
// missing a trailing slash, so that like POST requests (and the rest), the internal.trailing_slash_redirect
// route will handle it.
$app['url_matcher'] = $app->share(function () use ($app) {
    return new UrlMatcher($app['routes'], $app['request_context']);
});

$app->match('/{resource}', function($resource) use ($app) {
    if ($app['logger']) {
        $app['logger']->debug(sprintf('Appending a trailing slash for the request to `/%s`.', $resource));
    }

    $request = Request::create(
        '/' . $resource . '/',
        $app['request']->getMethod(),
        array_merge($app['request']->query->all(), $app['request']->request->all()),
        $app['request']->cookies->all(),
        $app['request']->files->all(),
        $app['request']->server->all(),
        $app['request']->getContent()
    );

    // Make an internal request based off the one that would have 404'd.
    // http://silex.sensiolabs.org/doc/usage.html#forwards
    return $app->handle($request, HttpKernelInterface::SUB_REQUEST);
})->assert('resource', '.*(?<!\/)$')->bind('internal.trailing_slash_redirect');
```

**Comment by ragboyjr** [comment]
So after looking through the code on this issue. The crux of the problem lies here: https://github.com/symfony/routing/blob/master/Route.php#L158

The path is *always* prefixed with a `/`. Normally this isn't an issue except for the case as discussed in this issue.

I did some debugging, and if you remove that line of code about the prepending slash, it all works. Because the Symfony route variables are marked private, you can't update them by extending the Route class. I think this is more of a Symfony issue than Silex.

A nice solution would be to have a route implementation that doesn't automatically prefix the path, and then when you define a route with a prefix, then defining the route as `$app->get('', function(){})` will actually work now. And for all other routes defined, you should always include the `/`. But this will be left up to the user to do that.

```php
$forum = $app['controllers_factory'];
$forum->get('', function () {
    return 'Forum home page';
});

// define "global" controllers
$app->get('/', function () use ($app) {
    dump($app['routes']->all());exit;
    return 'Main home page';
});
$app->get('/abc', function() {
    return 'abc';
});
$app->mount('/forum', $forum);
```

**Comment by alexkappa** [comment]
@ragboyjr you might be onto something here! Perhaps there's a way to have minimal impact in Symfony's routing and resolve this issue within Silex itself.

We could change the accessors in [`Symfony\Component\Routing\Route`](https://github.com/symfony/routing/blob/master/Route.php) and from [`Silex\Route`](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Route.php) overwrite the `setRoute` method to _not_ prefix routes with a slash.

Thoughts?

**Comment by ragboyjr** [comment]
@alexkappa 

Yes,

1. You'd need to make the variables protected in Symfony first.
2. Then I was thinking, in the Silex\Route, I was thinking we could add a flag for (is prefixed). If that flag is *not* set, then we just use the `parent::setPath`, if it is set, then we just set the path without the prefix.

So this change would only affect mounted routes **in** silex. This wouldn't be a BC break for Symfony. And then we'd need to update the documentation to reflect this specific change.

**Comment by ragboyjr** [comment]
@alexkappa, the boys at Symfony don't like the idea of making Route class with protected vars. Updating the setPath to take flag might work, but I'm not sure on how we'd get that to filter back down into silex because it's BC incompatible change with regards to extending the route class.

**Comment by alexkappa** [comment]
> I was thinking we could add a flag for (is prefixed). If that flag is not set, then we just use the `parent::setPath`, if it is set, then we just set the path without the prefix.

Yes something along those lines, but how will users pass that `$isPrefixed` argument? The `Route::setPath()` method is called from `Silex\ControllerCollection`.

I was thinking that perhaps we could supply a separate Route class which users can use instead of the original `Silex\Route`. [`Silex\Application`](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Application.php#L82-L85) is configurable, and the `route_class` and `route_factory` can be swapped for something else, so users can configure their `$app` with whatever routing they prefer. The downside however is that we'll introduce two very similar routing classes and people won't obviously see the difference.

Maybe configuring [`Silex\Route` with options](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Route.php#L38) which it already supports and replace `route_factory` to set this option.

**Comment by ragboyjr** [comment]
@alexkappa, not a bad idea at all. Here's a mock I did, and it actually works!

https://github.com/ragboyjr/Silex/commit/9eb3a45dffcdfe0339b12a6b66a898bebda645b1

**Comment by ragboyjr** [comment]
Also, @alexkappa, implementing this could be done kind of two ways. We either make the user explicitly choose to allow empty routes, or we implicitly allow it by only making mounted routes empty.

For explicitly, we could easily provide a parameter in the RoutingServiceProvider like 
```php
$app['allow_empty_routes'] = true;
```

and that will use the appropriate Route class in the application.

For implicitly, we could setup any mounted controller collection to use EmptyPathRoute as the default route instead of the normal route. So on non-mounted paths, all routes defined are on the normal route. And on mounted routes, all routes defined use the EmptyPathRoutes. 

Both options wouldn't be very difficult to do.

**Comment by sbczk** [comment]
I personally found this way more elegant instead of making sub requests

```php
$app = new Application();

$app->mount('/v1', new SomethingListProvider());
$app->mount('/v1/something', new SomethingRestProvider());

class SomethingListProvider implements ControllerProviderInterface
{
    public function connect(Application $app)
    {
        $app['something_list_controller'] = function () use ($app) {
            return new SomethingController($app);
        };

        $controller = $app['controllers_factory'];
        $controller->get('/something', 'something_list_controller:listAction')->bind(
            'something_list'
        );

        return $controller;
    }
}

class SomethingRestProvider implements ControllerProviderInterface
{
    public function connect(Application $app)
    {
        $app['something_rest_controller'] = function() use ($app) {
            return new SomethingController($app);
        };

        $controller = $app['controllers_factory'];
        $controller->get('/{id}', 'something_rest_controller:getAction')->bind(
            'something_get'
        );

        return $controller;
    }
}

```

**Comment by Sentence** [comment]
Check this Symfony mini-doc, I hope it helps:
[Redirect URLs with a Trailing Slash](https://symfony.com/doc/3.4/routing/redirect_trailing_slash.html)

Also in Symfony if you use your routes with trailing slashes, the non-trailing slashed routes will 301 redirected to tralining slashed routes.

**Comment by fabpot** [comment]
see symfony/symfony#26284

**Comment by evert** [comment]
It's nice to get some closure on this one =D
