### ISSUE TITLE
Support PHP 7

### ISSUE THREAD

**Issue by Tazmaniadroid** [silexphp/Silex#1548]
The framework silex 2.2 is support PHP 7, because i will use in this versión in PHP

**Comment by SpacePossum** [comment]
yes, Silex 2.2 supports all PHP 7 versions:
https://github.com/silexphp/Silex/blob/v2.2.0/composer.json#L18

**Comment by lracicot** [comment]
I would not say that it supports php 7.2, because `symfony/http-foundation (~2.8|^3.0)` is required by Silex 2.2, and that package triggers a warning when used with phpunit (see #1566).

So basically, Silex + SessionServiceProvider + PHPUnit seems to be broken in 7.2 when using NativeFileSessionHandler.

**Comment by fabpot** [comment]
Closing as PHP 7.2 is supported.
