### ISSUE TITLE
Error after update to v2.2.3

### ISSUE THREAD

**Issue by nictrace** [silexphp/Silex#1621]
After update to v2.2.3 I got a ClassNotFoundException, while class MessageFormatter was non found.
Rollback to 2.2.2 fixes it
[screenshot](https://screenshots.firefox.com/HBqMSmtSe6I4Xn7s/back.entilescraft.ru)

**Comment by SpacePossum** [comment]
Hi,
Looking at the code this error is caused because the code tries to load the `MessageFormatter` class which is available since SF 3.4.0  translation package. There is a BC-check for this in place but this doesn't seem to work for your setup.
Could you run the following command `composer info` for both the 2.2.2 and 2.2.3 setup (in the root of your project) and share the output? I'm curious about which other packages are installed by composer and think this info will help to figure out what is wrong.

**Comment by stof** [comment]
The issue here is that the TranslationServiceProvider checks the implementation it should use based on `Kernel::VERSION_ID < 30400`. But this constant gives you the version of HttpKernel being used, not the version of symfony/translation being used.

Doing version checks on the kernel version does not work fine when installing components separately.

**Comment by hkdobrev** [comment]
I think class checks are better even if they look hacky as well.

**Comment by stof** [comment]
well, a class check is exactly what we need here: detecting the feature itself instead of trying to detect the version (frontend guys have learned this since years btw)

**Comment by stof** [comment]
@nictrace what would be interesting is the non-working list.

**Comment by nictrace** [comment]
completely the same, except silex version 2.2.3

**Comment by SpacePossum** [comment]
thanks for the info @nictrace 

```
symfony/http-kernel         v3.4.4
symfony/translation         v3.2.14 
```

the confirms what @stof stated and should be patched with a class check indeed.
@stof which branch should the fix target, this faulty code is not in `2.2.1` nor in the `master` ?

**Comment by SpacePossum** [comment]
@fabpot (cc @stof ) any help about which branch to target is welcome so people know what to target for bug fix for 2.2.4 PR's :)

**Comment by fabpot** [comment]
We don't have a 2.2 branch. We are always fixing bug on the master branch. So, the fix should go on master and be part of the 2.3 series. That's how we also work on Twig, and that allows to reduce the maintenance workload. In any case, 2.3 is just about adding Symfony 4 support, so no big deal to jump to 2.3.0 when it's ready IMHO.

**Comment by fabpot** [comment]
... and now that I read the thread again, I understand the issue :) Let's say that we can to an exception here if that really important and create a 2.2.4 release with the bug fix. If someone can work on a patch, I will happily apply it locally and make a release.

**Comment by jibundeyare** [comment]
Is a patch like the following totally out of scope or not ?
```
         $app['translator.message_selector'] = function () {
-            if (Kernel::VERSION_ID < 30400) {
+            if (class_exists('Symfony\Component\Translation\MessageSelector')) {
                 return new MessageSelector();
             }
```
If it doesn't fit, please do not bash me.

**Comment by SpacePossum** [comment]
thanks @jibundeyare , looks good (as an alternative there is https://github.com/silexphp/Silex/pull/1627 if needed : ) )

**Comment by jibundeyare** [comment]
@SpacePossum your PR looks much better to me.

**Comment by SpacePossum** [comment]
It has been merged and shipped by fabpot , enjoy the new release with the fix!
